### PR TITLE
Config fix

### PR DESCRIPTION
**Pull request by edewit**
same fix but then against the 2.2.x branch

### CODE REVIEW

**Comment by secondsun** [comment]
Would you mind copying the Test from https://github.com/aerogear/aerogear-android-push/pull/51/?

**Comment by edewit** [comment]
sorry I was cherry picking, added the test

**Comment by secondsun** [comment]
Can you flatten ca0908c...00f7c85?  After that we will be good to go.

**Comment by danielpassos** [comment]
:+1:

**Pull request merged**
