### PR TITLE
Update topic validation pattern to FCM

### PR DESCRIPTION
**Pull request by danielpassos**
Related of [AGDROID-568](https://issues.jboss.org/browse/AGDROID-568)

### CODE REVIEW

**Comment by matzew** [comment]
+1

looks good to me

**Comment by secondsun** [comment]
@danielpassos LGTM, has anyone tested it in an app yet?

**Comment by danielpassos** [comment]
@secondsun I have tested it, but would be cool if anyone can double check. 

screenshot 2017-06-26 10 32 48

**Comment by secondsun** [comment]
LGTM

**Pull request merged**
