### PR TITLE
Prevent try unregister after first success attempt

### PR DESCRIPTION
**Pull request by danielpassos**
See [AGDROID-368](https://issues.jboss.org/browse/AGDROID-368)

### CODE REVIEW

**Comment by danielpassos** [comment]
@secondsun @matzew Could you review that?

**Comment by danielpassos** [comment]
@secondsun @matzew Could you review that?

**Comment by matzew** [comment]
Perhaps worth to mention the 'new' behavior on here:
https://github.com/danielpassos/aerogear-android-push/blob/prevent-unncessary-unregister/aerogear-android-push/src/main/java/org/jboss/aerogear/android/unifiedpush/PushRegistrar.java#L33-L40

that an ISE is thrown, in case unreg. has been executed before ?

**Comment by danielpassos** [comment]
@matzew I'm not 100% sure about that, because ISE is an implementation thing,

**Comment by qmx** [comment]
@matzew *if* you really want to add info about the exception, then the way is adding a custom exception and then documenting it. Something like `AlreadyUnregisteredException` mayhap?

**Comment by matzew** [comment]
that would be OK for me as well

On Mon, Feb 9, 2015 at 12:56 PM, Douglas Campos <notifications@github.com>
wrote:

> @matzew <https://github.com/matzew> *if* you really want to add info
> about the exception, then the way is adding a custom exception and then
> documenting it. Something like AlreadyUnregisteredException mayhap?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-android-push/pull/30#issuecomment-73497265>
> .
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by secondsun** [comment]
@matzew The request isn't "thrown" in the sense that the developer will wrap the unregister in a try/catch block.  The call back's onFailure method will be called with the Exception as the parameter.

**Comment by matzew** [comment]
:+1:

**Comment by matzew** [comment]
:+1: merged

**Pull request merged**
