### PR TITLE
Make variantID and secret required for AeroGearGCMPushConfiguration

### PR DESCRIPTION
**Pull request by danielpassos**
See: [AGDROID-343](https://issues.jboss.org/browse/AGDROID-343)

### CODE REVIEW

**Comment by danielpassos** [comment]
@matzew @secondsun Could you review that?

**Comment by secondsun** [comment]
Builds and green bars, yay!.

Do we need to make any updates to the quickstart and hello world apps?

**Comment by matzew** [comment]
:+1: tested the branch on my machine, works fine

**Comment by matzew** [comment]
@danielpassos can you rebase ?

**Comment by danielpassos** [comment]
@secondsun Nopz, nothing needs be updated

**Comment by danielpassos** [comment]
@matzew Rebased!

**Comment by matzew** [comment]
thanks, merged it

**Pull request merged**
