### PR TITLE
Ignore registration ACK

### PR DESCRIPTION
**Pull request by danielpassos**
See: [AGDROID-425](https://issues.jboss.org/browse/AGDROID-425)

### CODE REVIEW

**Comment by danielpassos** [comment]
@matzew @sebastienblanc @secondsun Could you test it?

**Comment by matzew** [comment]
Ok, that's not new and not related to the GCM 3.0, this ACK was alreayd part of the deprecated C2DM.

@danielpassos Since C2DM will be shut down later this year ([July 30, 2015](https://developers.google.com/android/c2dm/)), I am wondering if this KEY will be continued to be sent on the registration process ?

**Comment by matzew** [comment]
@danielpassos @secondsun if we remove this intent:
https://github.com/jboss-mobile/unified-push-helloworld/blob/master/android/app/src/main/AndroidManifest.xml#L59

I think the app would no longer get the message, right ?

However, we can't control that setting on our users app, so I think adding this check is the right thing, for now

**Comment by danielpassos** [comment]
> Ok, that's not new and not related to the GCM 3.0, this ACK was alreayd part of the deprecated C2DM.

Well we never received it or not with this message type. Because our example apps are displaying all push message received 

> Since C2DM will be shut down later this year (July 30, 2015), I am wondering if this KEY will be continued to be sent on the registration process ?

I'm note sure. Google is not so clear about it.

**Comment by danielpassos** [comment]
>if we remove this intent:
https://github.com/jboss-mobile/unified-push-helloworld/blob/master/android/app/src/main/AndroidManifest.xml#L59

I think the app would no longer get the message, right ?

Probably yes but need test.

**Comment by danielpassos** [comment]
@matzew I think Google answer your question [here](https://developers.google.com/cloud-messaging/android/client)

> If you want to support pre-4.4 KitKat devices, add the following action to the intent filter declaration for the receiver: &lt;action android:name="com.google.android.c2dm.intent.REGISTRATION" /&gt;

**Comment by matzew** [comment]
yeah, I saw that in the morning, but did not interpret is as: being around
after the end of C2DM :-)
Good pointer, thanks!


On Thu, Jun 18, 2015 at 9:03 PM, Daniel Passos <notifications@github.com>
wrote:

> @matzew <https://github.com/matzew> I think Google answer your question
> here <https://developers.google.com/cloud-messaging/android/client>
>
> If you want to support pre-4.4 KitKat devices, add the following action to
> the intent filter declaration for the receiver: <action
> android:name="com.google.android.c2dm.intent.REGISTRATION" />
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-android-push/pull/38#issuecomment-113259492>
> .
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by matzew** [comment]
:+1: on this being merged!

**Pull request merged**
