### PR TITLE
1.0.x

### PR DESCRIPTION
**Pull request by danielpassos**
Bump version

### CODE REVIEW

**Comment by danielpassos** [comment]
@secondsun @matzew Could you give it a spin?

**Comment by matzew** [comment]
@danielpassos sure thing, will do tomorrow

**Comment by matzew** [comment]
:+1:

**Comment by secondsun** [comment]
I'm having troubles building with maven 3.2.5.  I am investigating to see where the issue is.  It looks like it is the same problem as [here](https://developer.jboss.org/thread/251282)

**Comment by matzew** [comment]
Apache Maven 3.2.3 (33f8c3e1027c3ddde99d3cdebad2656a31e8fdf4;
2014-08-11T22:58:10+02:00)
Maven home: /Apache/maven/current
Java version: 1.8.0_20, vendor: Oracle Corporation


On Wed, Apr 15, 2015 at 2:16 PM, Hoyt Summers Pittman <
notifications@github.com> wrote:

> I'm having troubles building with maven 3.2.5. I am investigating to see
> where the issue is. It looks like it is the same problem as here
> <https://developer.jboss.org/thread/251282>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-android-push/pull/33#issuecomment-93364175>
> .
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by secondsun** [comment]
Yup, android-maven-plugin does not work with maven 3.2.5.

**Comment by danielpassos** [comment]
@secondsun Hrm, I think we had a problem with a version > 3.1.1 (not remember the version now) and that was the reason why we fixed the version 3.1.1 in [How To doc](https://aerogear.org/docs/guides/aerogear-android/how-to-build-aerogear-android/)

**Comment by secondsun** [comment]
@danielpassos Let's just put a validator to fail the build if you are >= 3.2.5 then

**Comment by matzew** [comment]
@danielpassos @secondsun what's the status here ?

**Comment by secondsun** [comment]
I think the status is we need to update the docs to record the requirement for maven 3.2.5+ and update the enforcer to require it and provide useful feedback when stuff fails.

**Comment by matzew** [comment]
Should we just close and just discontinue 1.0.x ? 

(now that 1.1.0.Final is coming VERY soon ? )

**Comment by danielpassos** [comment]
Yes!

**Pull request closed without merging**
