### PR TITLE
Update travis to use new infrastructure and bump to Android 22

### PR DESCRIPTION
**Pull request by danielpassos**

### CODE REVIEW

**Comment by secondsun** [comment]
-1 until the build passes if we are doing travis things.
Do you need extra eyes on it?

**Comment by danielpassos** [comment]
I gave up the run `push` on @travis-ci anyway this PR is more about migrate to a new machine and update the project to Android 22

**Comment by secondsun** [comment]
Have a new yml
```yml
sudo: false # See: docs.travis-ci.com/user/migrating-from-legacy

language: android

jdk:
  - oraclejdk8
  - oraclejdk7

android:
  components:
    - platform-tools
    - tools
    - build-tools-22.0.1
    - android-22
    - addon-google_apis-google-22
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-addon-google_apis-google-22
    - extra-google-google_play_services    

notifications:
  irc: "irc.freenode.org#aerogear"

env:
  global:
    - RELEASE_VERSION=$(grep "<version>" pom.xml | tr "\n" ":" | cut -d ':' -f1 | sed s/\<version\>//g| sed s/\"//g| sed s/\<\\/version\>//g | tr -d ' ')
  matrix:
    - ANDROID_SDK=android-22 ANDROID_EMULATOR="Google Inc.:Google APIs:22" ANDROID_ABI=google_apis/armeabi-v7a

before_install:

  #################################################
  ########## maven-android-sdk-deployer ###########
  #################################################

  # Checkout maven-android-sdk-deployer
  - git clone git://github.com/mosabua/maven-android-sdk-deployer.git

  # Install android maven repository
  - cd $PWD/maven-android-sdk-deployer/platforms/$ANDROID_SDK
  - mvn install -N --quiet
  - cd -

  - cd $PWD/maven-android-sdk-deployer/repositories
  - mvn install --quiet
  - cd -

  #################################################
  ############ Snapshot dependencies ##############
  #################################################

  # AeroGear Android Core
  - git clone git://github.com/aerogear/aerogear-android-core.git
  - cd $PWD/aerogear-android-core
  - mvn install -N --quiet
  - cd -

  # AeroGear Android Pipe
  - git clone git://github.com/aerogear/aerogear-android-pipe.git
  - cd $PWD/aerogear-android-pipe
  - mvn install -DskipTests -fn --quiet
  - cd -

before_script:

  # Create emulator
  - echo no | android create avd --force -n test -t "$ANDROID_EMULATOR" --abi "$ANDROID_ABI"

script:
  - mvn install -Drelease
  - cd aerogear-android-push-test
  - mvn package -DskipTests=true;

  - emulator -avd test -no-skin -no-audio -no-window&
  - wget https://raw.githubusercontent.com/travis-ci/travis-cookbooks/master/ci_environment/android-sdk/files/default/android-wait-for-emulator
  - chmod a+x ./android-wait-for-emulator
  - ./android-wait-for-emulator
  - adb shell input keyevent 82
  - adb shell df
  - adb install target/aerogear-android-push-test-$RELEASE_VERSION.apk
  - mvn -X android:instrument
```

**Comment by danielpassos** [comment]
We are awesome and green :)

**Comment by secondsun** [comment]
+1

**Pull request merged**
