### PR TITLE
Prevent try unregister after first success attempt

### PR DESCRIPTION
**Pull request by danielpassos**
See [AGDROID-368](https://issues.jboss.org/browse/AGDROID-368)

### CODE REVIEW

**Comment by danielpassos** [comment]
@secondsun @matzew Could you review that?

**Comment by matzew** [comment]
:+1:

**Comment by matzew** [comment]
:tada: thanks for the PR

**Comment by matzew** [comment]
@danielpassos should we run a new release for 1.0.1 ?

**Pull request merged**
