### PR TITLE
Removing http status

### PR DESCRIPTION
**Pull request by secondsun**
@danielpassos @danbev @lholmquist :eyes: ?

### CODE REVIEW

**Comment by lholmquist** [comment]
getting this error on the tests,  https://gist.github.com/lholmquist/db052cc112f8c975a29f with my samsung GT-I9505

**Comment by danielpassos** [comment]
lh

**Comment by danielpassos** [comment]
@lholmquist Hrm, I think it's not the first time we have this error in your device.

**Comment by danielpassos** [comment]
:+1:  It works on my machine :)

**Pull request merged**
