### PR TITLE
Fix categories config - 2.2.x

### PR DESCRIPTION
**Pull request by danielpassos**
See [AGDROID-502](https://issues.jboss.org/browse/AGDROID-502)

### CODE REVIEW

**Comment by danielpassos** [comment]
@secondsun Could you give it a spin?

**Comment by secondsun** [comment]
Can you rebase this on the latest head for 2.2.x?

**Comment by danielpassos** [comment]
@secondsun Done!

**Comment by danielpassos** [comment]
It was fixed by @edewit in https://github.com/aerogear/aerogear-android-push/pull/51

**Pull request closed without merging**
