### PR TITLE
Version updates

### PR DESCRIPTION
**Pull request by secondsun**

### CODE REVIEW

**Comment by danielpassos** [comment]
:+1:

**Comment by danielpassos** [comment]
@secondsun I think you should remove my categories fix commit.

**Comment by secondsun** [comment]
@danielpassos done

**Comment by matzew** [comment]
:+1:

On Tuesday, 29 March 2016, Hoyt Summers Pittman <notifications@github.com>
wrote:

> @danielpassos <https://github.com/danielpassos> done
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-android-push/pull/57#issuecomment-202659078>
>


-- 
Sent from Gmail Mobile

**Pull request merged**
